---
title: "Visualisation Challenge"
tutorial:
  id: "yousaydata.vischallenge"
  version: 3.0.0
output:
  learnr::tutorial:
    progressive: true
    allow_skip: true
    theme: simplex
    includes:
      before_body: "./www/branding.html"
runtime: shiny_prerendered
description: >
  Learn some basic concepts of ggplot2.
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(tidytuesdayR)

rolling_stone <- tt_load(2024, week = 19)[["rolling_stone"]]
gradethis::gradethis_setup()
knitr::opts_chunk$set(echo = FALSE)
```

## Challenge 1

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity)) +
  geom_point() +
  geom_smooth(se=F)
```

```{r challenge1, exercise=TRUE}

```

## Challenge 2

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity)) +
  geom_smooth(aes(group=artist_gender), se=F) +
  geom_point()
```

```{r challenge2, exercise=TRUE}

```

## Challenge 3 

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity, col=artist_gender)) +
  geom_smooth(se=F) +
  geom_point()
```

```{r challenge3, exercise=TRUE}

```

## Challenge 4

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity)) +
  geom_point(aes(col=artist_gender)) +
  geom_smooth(se=F)
```

```{r challenge4, exercise=TRUE}

```

## Challenge 5

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity)) +
  geom_point(aes(col=artist_gender)) +
  geom_smooth(aes(linetype=artist_gender), se=F)
```

```{r challenge5, exercise=TRUE}

```

## Challenge 6

Reproduce the graph:

```{r}
ggplot(rolling_stone, aes(debut_album_release_year,spotify_popularity)) +
  geom_point(size = 4, col = "white") +
  geom_point(aes(col=artist_gender))
```

```{r challenge6, exercise=TRUE}

```
